all :
	make all -C lagrangeShapeFct_plot
	make all -C lagrangeShapeFctDeriv_plot
	make all -C superElement_plot

gnuplot :
	make gnuplot -C lagrangeShapeFct_plot

python :
	make python -C superElement_plot

clean:
	make clean -C lagrangeShapeFct_plot
	make clean -C lagrangeShapeFctDeriv_plot
	make clean -C superElement_plot